### ISSUE TITLE
This is a February 2011, not September 2010.

### ISSUE THREAD

**Issue by ghost** [JohnCartoonist/Minecraft_September_20th_2010_launcher#1]
The original design that my launcher forked upon was from June 2010, and the new design didn't come to light until the release of Beta 1.3, which was February 2011.

You can find an early design in this archived tumblr link. Sorry for being so late with it. Just wanted to clarify:

https://web.archive.org/web/20210224014230/https://notch.tumblr.com/post/2857128986/minecraft-beta-1202

**Comment by JohnCartoonist** [comment]
I appreciate you telling me this because it was a mistake of mine. Apparently, I mislabeled it, so my apologies for that. I will rename the repository. Thank you for the feedback!
